STATE_CODE_MAP = {
    "ala": "AL",
    "alaska": "AK",
    "ariz ": "AZ ",
    "ark": "AR",
    "calif": "CA",
    "colo ": "CO ",
    "conn": "CT",
    "dc": "DC",
    "del": "DE",
    "fla": "FL",
    "ga": "GA",
    "hawaii": "HI",
    "idaho ": "ID ",
    "ill ": "IL",
    "ind ": "IN ",
    "iowa": "IA",
    "kans ": "KS ",
    "ky": "KY",
    "la": "LA",
    "maine": "ME",
    "mass": "MA",
    "md": "MD",
    "mich ": "MI ",
    "minn ": "MN ",
    "miss": "MS",
    "mo": "MO",
    "mont": "MT",
    "nc": "NC",
    "nd": "ND",
    "nh ": "NH ",
    "nj ": "NJ ",
    "nm": "NM",
    "ny": "NY",
    "nebr": "NE",
    "nev": "NV",
    "ohio": "OH",
    "okla ": "OK ",
    "ore": "OR",
    "pa ": "PA ",
    "ri": "RI",
    "sc": "SC",
    "sd": "SD",
    "tenn": "TN",
    "tex": "TX",
    "utah ": "UT ",
    "va": "VA",
    "vt": "VT",
    "wva ": "WV ",
    "wash": "WA",
    "wis": "WI",
    "wyo": "WY",
}
